#!/bin/sh

# kitfox: make a customized Firefox.
# Unpack browser/omni.ja, apply patches, then package it back up.
# For more details on the process, see:
#  http://shallowsky.com/blog/tech/web/modifying-omni.ja.html

# Either run this from the downloaded and unpacked Firefox directory,
# or pass the path to that directory as the first argument.

# On a system where firefox is installed as a package, pass it the
# location of the firefox files, e.g. /usr/lib/firefox on Debian/Ubuntu.

# You'll need to re-run this every time Firefox updates browser/omni.ja.
# That doesn't necessarily happen in every Firefox update, but if
# you include a harmless patch to the default URLbar message,
# you can tell when it changes, which will tell you when you need
# to re-run the script. (See "silly message" below.)

# based on kitfox-patch script found in git@github.com:akkana/scripts.git

FIREFOXDIR=${1:-/usr/lib64/firefox}
if [ x"$FIREFOXDIR" = "x" ]; then
  echo "Pass location of firefox files, e.g. /usr/lib/firefox"
  exit 1
else
  # In zsh, $FIREFOXDIR:A would do this.
  FIREFOXDIR=$(realpath $FIREFOXDIR)
fi

if [ ! -d "$FIREFOXDIR" ]; then
  echo 'Usage: kitfoxpatch [FIREFOXDIR]'
  exit 1
fi

echo Firefox dir is $FIREFOXDIR

realomni=$FIREFOXDIR/browser/omni.ja

OMNITMPDIR=/tmp/omni

# BACKUP_OMNI=$FIREFOXDIR/browser-omni-backup.ja
BACKUP_OMNI=$HOME/browser-omni-backup-$(date +%Y-%m-%d).ja

echo "Making directory $OMNITMPDIR ..."
rm -rf $OMNITMPDIR
mkdir -p $OMNITMPDIR
cd $OMNITMPDIR || exit

echo "Unzipping in $OMNITMPDIR ..."
unzip -q $realomni

echo "Making changes ..."

########################################
# PUT YOUR DESIRED CHANGE HERE.
# XXX change this to use patch format.

#
# Put a silly message in the URLbar you see on empty tabs.
# The point of this is that when it disappears, you know Firefox
# has updated and you need to re-run this script.
#
sed -i 's/or enter address/or just twiddle your thumbs/' chrome/en-US/locale/browser/browser.dtd chrome/en-US/locale/browser/browser.properties

#
# Get rid of the reserved Ctrl-W bindings in text fields:
#
# sed -i '/key_close/s/ reserved="true"//' chrome/browser/content/browser/browser.xul
# browser.xul got renamed to browser.xhtml in Firefox 69.0:
#sed -i '/key_close/s/ reserved="true"//' chrome/browser/content/browser/browser.xhtml

#
# change the CHECKING state to NO_UPDATES_FOUND and don't bother checking
#
sed -i 's/STATUS.CHECKING/STATUS.NO_UPDATES_FOUND/;s:\(this.checker.checkForUpdates\)://\1:' modules/AppUpdater.jsm

# End of patches
########################################

echo "Repackaging ..."
# repackage omni.ja:
zip -qr9XD /tmp/newomni.ja *

echo "Backing up original to $BACKUP_OMNI"
cp $FIREFOXDIR/browser/omni.ja $BACKUP_OMNI

echo "Trying to copy /tmp/newomni.ja to $realomni"
#echo "If this doesn't work, try sudo cp /tmp/newomni.ja $realomni"
echo
sudo cp /tmp/newomni.ja $realomni && echo "Copied new omni.ja into $realomni"

